services:

    mosquitto:
        build:
            context: mosquitto
            dockerfile: Dockerfile
        container_name: auton8-mosquitto
        restart: unless-stopped
        user: ${PUID}:${PGID}
        environment:
            - NO_COLOR=true
        volumes:
            - ./mosquitto/config:/mosquitto/config
            - mosquitto-data:/mosquitto/data
        # expose to HOST loopback only (not the LAN):
        ports:
            - "127.0.0.1:1883:1883"
        command: >
            sh -c "touch /mosquitto/config/passwd && /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf"

    n8n:
        image: n8nio/n8n:latest
        container_name: auton8-n8n
        restart: unless-stopped
        user: ${PUID}:${PGID}
        environment:
            - N8N_HOST=${N8N_HOST:-"localhost"}
            - N8N_PORT=${N8N_PORT:-5678}
            - N8N_EDITOR_BASE_URL=${N8N_EDITOR_BASE_URL:-"http://localhost:5678"}
            - N8N_PROTOCOL=http
            - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
            - N8N_DIAGNOSTICS_ENABLED=false
            - N8N_HIRING_BANNER_ENABLED=false
            - N8N_HIDE_USAGE_PAGE=true
            - TZ=${TZ}
            - GENERIC_TIMEZONE=${TZ}
            - DB_TYPE=sqlite
            - DB_SQLITE_VACUUM_ON_STARTUP=true
            - NO_COLOR=true
        volumes:
            - n8n-data:/home/node/.n8n
        ports:
            - "127.0.0.1:5678:5678"
        depends_on:
            - mosquitto

volumes:
    mosquitto-data:
    n8n-data:
