services:

    mosquitto:
        image: eclipse-mosquitto:2
        container_name: auton8-mosquitto
        restart: unless-stopped
        volumes:
            - mosquitto-config:/mosquitto/config
            - mosquitto-data:/mosquitto/data
        # expose to HOST loopback only (not the LAN):
        ports:
            - "127.0.0.1:1883:1883"
        command: >
            sh -c "touch /mosquitto/config/passwd &&
                   /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf"

    n8n:
        image: n8nio/n8n:latest
        container_name: auton8-n8n
        restart: unless-stopped
        environment:
            - TZ=${TZ}
            - N8N_HOST=${N8N_HOST}
            - N8N_PORT=${N8N_PORT}
            - N8N_EDITOR_BASE_URL=${N8N_EDITOR_BASE_URL}
            - N8N_PROTOCOL=http
            - GENERIC_TIMEZONE=${TZ}
            # Local file storage (sqlite)
            - DB_TYPE=sqlite
            - DB_SQLITE_VACUUM_ON_STARTUP=true
        volumes:
            - n8n-data:/home/node/.n8n
        ports:
            - "127.0.0.1:5678:5678"
        depends_on:
            - mosquitto


volumes:
    mosquitto-config:
    mosquitto-data:
    n8n-data:
