services:

    mosquitto-init:
        build:
            context: mosquitto
            dockerfile: Dockerfile
        container_name: auton8-mosquitto-init
        restart: no # run once, then exit
        user: ${PUID}:${PGID}
        environment:
            - MQTT_USER=${MQTT_USER}
            - MQTT_PASS=${MQTT_PASS}
        volumes:
            - ./mosquitto/config:/mosquitto/config
        command: >
            sh -c '
              touch /mosquitto/config/passwd &&
              chmod 0700 /mosquitto/config/passwd &&
              mosquitto_passwd -b /mosquitto/config/passwd "$$MQTT_USER" "$$MQTT_PASS"
            '

    mosquitto:
        build:
            context: mosquitto
            dockerfile: Dockerfile
        container_name: auton8-mosquitto
        restart: unless-stopped
        user: ${PUID}:${PGID}
        volumes:
            - ./mosquitto/config:/mosquitto/config # directory mount
            - mosquitto-data:/mosquitto/data # managed volume
        ports:
            - "127.0.0.1:1883:1883" # expose to localhost only
        command: mosquitto -c /mosquitto/config/mosquitto.conf
        depends_on:
            mosquitto-init:
                condition: service_completed_successfully

    n8n:
        image: n8nio/n8n:latest
        container_name: auton8-n8n
        restart: unless-stopped
        user: ${PUID}:${PGID}
        environment:
            - N8N_HOST=${N8N_HOST:-"localhost"}
            - N8N_PORT=${N8N_PORT:-5678}
            - N8N_EDITOR_BASE_URL=${N8N_EDITOR_BASE_URL:-"http://localhost:5678"}
            - N8N_PROTOCOL=http
            - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=false
            - N8N_DIAGNOSTICS_ENABLED=false
            - N8N_HIRING_BANNER_ENABLED=false
            - N8N_HIDE_USAGE_PAGE=true
            - TZ=${TZ}
            - GENERIC_TIMEZONE=${TZ}
            - DB_TYPE=sqlite
            - DB_SQLITE_VACUUM_ON_STARTUP=true
            - NO_COLOR=true
        volumes:
            - n8n-data:/home/node/.n8n
        ports:
            - "127.0.0.1:5678:5678"
        depends_on:
            - mosquitto

volumes:
    mosquitto-data:
    n8n-data:
